---
- name: build requires (ruby spec)
  yum: name={{ item }} state=present
  with_items: rbenv.build_requires.spec
- name: build requires (compiler, and more)
  yum: name={{ item }} state=present
  with_items: rbenv.build_requires.others
- name: clone this project
  git: >
        repo=https://github.com/rbenv/rbenv.git
        dest={{ rbenv.install_dir }} update=no
- name: clone this project (build environment)
  git: >
        repo=https://github.com/rbenv/ruby-build.git
        dest={{ rbenv.install_dir }}plugins/ruby-build/ update=no
- name: generate setup script ==> /etc/profile.d/rbenv_setup.sh
  template: src=bash/rbenv_setup.sh dest=/etc/profile.d/
- name: build ruby ({{ rbenv.ruby.install_versions }})
  shell: >
          $SHELL --login -c 'rbenv versions | \grep {{ item }}
          || {{ rbenv.ruby.make_opts }} rbenv install {{ item }}'
  with_items: rbenv.ruby.install_versions
- name: set global environment ({{ rbenv.ruby.global }})
  shell: $SHELL --login -c 'rbenv global {{ rbenv.ruby.global }}'
- name: set local environment
  shell: >
          $SHELL --login -c 'rbenv local {{ item.key }}'
          chdir={{ item.value }}
  with_dict: "{{ rbenv.ruby.local }}"