---
- name: verify elixir installation
  command: iex --version
  become: no
  register: which_iex
  ignore_errors: yes
- name: compilation (clone)
  git: >
        repo=https://github.com/elixir-lang/elixir.git
        dest={{ elixir_lang.build_dir }} update=no
        version={{ elixir_lang.version }}
- name: compilation (build started)
  command: make clean install chdir={{ elixir_lang.build_dir }}
  when: which_iex | failed