---
- name: install package
  yum: name={{ item }} state=present
  with_items:
    - nginx
    - python-pycurl
- name: settings for wildcard domain name system
  template: src=proxy/automated_xip.conf dest=/etc/nginx/conf.d/